server:
  port: 7788
  servlet:
    context-path: /
spring:
  datasource:
    guard:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://124.221.255.113:3306/dataguard?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
      username: root
      password: 123456

    dmsql:
      driver-class-name: dm.jdbc.driver.DmDriver
      jdbc-url: jdbc:dm://127.0.0.2:5236
      username: SYSDBA
      password: 1234567890


#mybatis  120.79.89.15=HY服务器  1234567890    10.89.10.229:10236   LG_SZSB   '#Lg_Szsb.789'     172.16.185.140
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.example.demo.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      db-column-underline: true  # 驼峰下划线转换
      refresh-mapper: true
      logic-delete-value: 1  # 逻辑删除配置
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

  redis:
    open:  false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接 池中的最小空闲连接  124.223.213.40
